-- =====================================================
-- SCRIPT DE DATOS DE PRUEBA
-- Ordenado según dependencias de claves foráneas
-- =====================================================

-- =====================================================
-- NIVEL 1: TABLAS INDEPENDIENTES (Sin dependencias)
-- =====================================================

-- 1. OPERACIONES
INSERT INTO OPERACIONES (NOMBRE_OPERACION) VALUES ('Crear');
INSERT INTO OPERACIONES (NOMBRE_OPERACION) VALUES ('Modificar');
INSERT INTO OPERACIONES (NOMBRE_OPERACION) VALUES ('Eliminar');
INSERT INTO OPERACIONES (NOMBRE_OPERACION) VALUES ('Consultar');
INSERT INTO OPERACIONES (NOMBRE_OPERACION) VALUES ('Inactivar');

-- 2. INSTITUCIONES
INSERT INTO INSTITUCIONES (NOMBRE) VALUES ('Hospital Central');
INSERT INTO INSTITUCIONES (NOMBRE) VALUES ('Clínica San José');
INSERT INTO INSTITUCIONES (NOMBRE) VALUES ('Centro Médico Norte');
INSERT INTO INSTITUCIONES (NOMBRE) VALUES ('Hospital Pediátrico');

-- 3. PERFILES
INSERT INTO PERFILES (NOMBRE_PERFIL, ESTADO) VALUES ('Administrador', 'ACTIVO');
INSERT INTO PERFILES (NOMBRE_PERFIL, ESTADO) VALUES ('Aux administrativo', 'ACTIVO');
INSERT INTO PERFILES (NOMBRE_PERFIL, ESTADO) VALUES ('Técnico', 'ACTIVO');
INSERT INTO PERFILES (NOMBRE_PERFIL, ESTADO) VALUES ('Usuario', 'ACTIVO');

-- 4. FUNCIONALIDADES
INSERT INTO FUNCIONALIDADES (NOMBRE_FUNCIONALIDAD, ESTADO, RUTA) VALUES ('Gestión de Usuarios', 'ACTIVO', '/usuarios');
INSERT INTO FUNCIONALIDADES (NOMBRE_FUNCIONALIDAD, ESTADO, RUTA) VALUES ('Gestión de Equipos', 'ACTIVO', '/equipos');
INSERT INTO FUNCIONALIDADES (NOMBRE_FUNCIONALIDAD, ESTADO, RUTA) VALUES ('Gestión de Ubicaciones', 'ACTIVO', '/ubicaciones');
INSERT INTO FUNCIONALIDADES (NOMBRE_FUNCIONALIDAD, ESTADO, RUTA) VALUES ('Gestión de Intervenciones', 'ACTIVO', '/intervenciones');
INSERT INTO FUNCIONALIDADES (NOMBRE_FUNCIONALIDAD, ESTADO, RUTA) VALUES ('Reportes', 'ACTIVO', '/reportes');

-- 5. TIPOS_INTERVENCIONES
INSERT INTO TIPOS_INTERVENCIONES (NOMBRE_TIPO, ESTADO) VALUES ('Mantenimiento Preventivo', 'ACTIVO');
INSERT INTO TIPOS_INTERVENCIONES (NOMBRE_TIPO, ESTADO) VALUES ('Mantenimiento Correctivo', 'ACTIVO');
INSERT INTO TIPOS_INTERVENCIONES (NOMBRE_TIPO, ESTADO) VALUES ('Calibración', 'ACTIVO');
INSERT INTO TIPOS_INTERVENCIONES (NOMBRE_TIPO, ESTADO) VALUES ('Reparación', 'ACTIVO');
INSERT INTO TIPOS_INTERVENCIONES (NOMBRE_TIPO, ESTADO) VALUES ('Instalación', 'ACTIVO');

-- 6. TIPOS_EQUIPOS
INSERT INTO TIPOS_EQUIPOS (NOMBRE_TIPO, ESTADO) VALUES ('Monitor', 'ACTIVO');
INSERT INTO TIPOS_EQUIPOS (NOMBRE_TIPO, ESTADO) VALUES ('Ventilador', 'ACTIVO');
INSERT INTO TIPOS_EQUIPOS (NOMBRE_TIPO, ESTADO) VALUES ('Bomba de Infusión', 'ACTIVO');
INSERT INTO TIPOS_EQUIPOS (NOMBRE_TIPO, ESTADO) VALUES ('Desfibrilador', 'ACTIVO');
INSERT INTO TIPOS_EQUIPOS (NOMBRE_TIPO, ESTADO) VALUES ('Electrocardiógrafo', 'ACTIVO');

-- 7. MARCAS_MODELO
INSERT INTO MARCAS_MODELO (NOMBRE, ESTADO) VALUES ('Philips', 'ACTIVO');
INSERT INTO MARCAS_MODELO (NOMBRE, ESTADO) VALUES ('GE Healthcare', 'ACTIVO');
INSERT INTO MARCAS_MODELO (NOMBRE, ESTADO) VALUES ('Siemens', 'ACTIVO');
INSERT INTO MARCAS_MODELO (NOMBRE, ESTADO) VALUES ('Drager', 'ACTIVO');
INSERT INTO MARCAS_MODELO (NOMBRE, ESTADO) VALUES ('Mindray', 'ACTIVO');

-- 8. PAISES
INSERT INTO PAISES (NOMBRE, ESTADO) VALUES ('Uruguay', 'ACTIVO');
INSERT INTO PAISES (NOMBRE, ESTADO) VALUES ('Estados Unidos', 'ACTIVO');
INSERT INTO PAISES (NOMBRE, ESTADO) VALUES ('Alemania', 'ACTIVO');
INSERT INTO PAISES (NOMBRE, ESTADO) VALUES ('China', 'ACTIVO');
INSERT INTO PAISES (NOMBRE, ESTADO) VALUES ('Holanda', 'ACTIVO');

-- =====================================================
-- NIVEL 2: TABLAS CON 1 DEPENDENCIA
-- =====================================================

-- 9. PROVEEDORES_EQUIPOS
INSERT INTO PROVEEDORES_EQUIPOS (NOMBRE, ESTADO, ID_PAIS) VALUES ('MedSupply Uruguay', 'ACTIVO', 1);
INSERT INTO PROVEEDORES_EQUIPOS (NOMBRE, ESTADO, ID_PAIS) VALUES ('Philips Medical', 'ACTIVO', 2);
INSERT INTO PROVEEDORES_EQUIPOS (NOMBRE, ESTADO, ID_PAIS) VALUES ('Siemens Healthineers', 'ACTIVO', 3);
INSERT INTO PROVEEDORES_EQUIPOS (NOMBRE, ESTADO, ID_PAIS) VALUES ('Mindray International', 'ACTIVO', 4);
INSERT INTO PROVEEDORES_EQUIPOS (NOMBRE, ESTADO, ID_PAIS) VALUES ('Drager Medical', 'ACTIVO', 5);

-- 10. MODELOS_EQUIPOS
INSERT INTO MODELOS_EQUIPOS (ID_MARCA, NOMBRE, ESTADO) VALUES (1, 'IntelliVue MX40', 'ACTIVO');
INSERT INTO MODELOS_EQUIPOS (ID_MARCA, NOMBRE, ESTADO) VALUES (1, 'IntelliVue MX800', 'ACTIVO');
INSERT INTO MODELOS_EQUIPOS (ID_MARCA, NOMBRE, ESTADO) VALUES (2, 'CARESCAPE B650', 'ACTIVO');
INSERT INTO MODELOS_EQUIPOS (ID_MARCA, NOMBRE, ESTADO) VALUES (3, 'MAGLIFE C+', 'ACTIVO');
INSERT INTO MODELOS_EQUIPOS (ID_MARCA, NOMBRE, ESTADO) VALUES (4, 'Fabius Plus', 'ACTIVO');
INSERT INTO MODELOS_EQUIPOS (ID_MARCA, NOMBRE, ESTADO) VALUES (5, 'BeneView T8', 'ACTIVO');

-- 11. UBICACIONES
INSERT INTO UBICACIONES (NOMBRE, SECTOR, PISO, NUMERO, CAMA, ID_INSTITUCION, ESTADO) VALUES ('UTI 1', 'Terapia Intensiva', 2, 1, 1, 1, 'ACTIVO');
INSERT INTO UBICACIONES (NOMBRE, SECTOR, PISO, NUMERO, CAMA, ID_INSTITUCION, ESTADO) VALUES ('UTI 2', 'Terapia Intensiva', 2, 1, 2, 1, 'ACTIVO');
INSERT INTO UBICACIONES (NOMBRE, SECTOR, PISO, NUMERO, CAMA, ID_INSTITUCION, ESTADO) VALUES ('Quirófano 1', 'Quirófanos', 1, 1, NULL, 1, 'ACTIVO');
INSERT INTO UBICACIONES (NOMBRE, SECTOR, PISO, NUMERO, CAMA, ID_INSTITUCION, ESTADO) VALUES ('Quirófano 2', 'Quirófanos', 1, 2, NULL, 1, 'ACTIVO');
INSERT INTO UBICACIONES (NOMBRE, SECTOR, PISO, NUMERO, CAMA, ID_INSTITUCION, ESTADO) VALUES ('Emergencias', 'Emergencias', 0, 1, 1, 1, 'ACTIVO');
INSERT INTO UBICACIONES (NOMBRE, SECTOR, PISO, NUMERO, CAMA, ID_INSTITUCION, ESTADO) VALUES ('Pediatría 1', 'Pediatría', 3, 1, 1, 4, 'ACTIVO');
INSERT INTO UBICACIONES (NOMBRE, SECTOR, PISO, NUMERO, CAMA, ID_INSTITUCION, ESTADO) VALUES ('Consultorio 1', 'Consultorios', 1, 1, NULL, 2, 'ACTIVO');

-- =====================================================
-- NIVEL 3: TABLAS CON MÚLTIPLES DEPENDENCIAS
-- =====================================================

-- 12. USUARIOS
INSERT INTO USUARIOS (CEDULA, NOMBRE, APELLIDO, ID_PERFIL, ID_INSTITUCION, EMAIL, NOMBRE_USUARIO, CONTRASENIA, ESTADO, FECHA_NACIMIENTO) 
VALUES ('12345678', 'Juan', 'Pérez', 1, 1, 'admin@hospital.com', 'admin', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iKTVEFDi', 'ACTIVO', TO_DATE('1985-03-15', 'YYYY-MM-DD'));

INSERT INTO USUARIOS (CEDULA, NOMBRE, APELLIDO, ID_PERFIL, ID_INSTITUCION, EMAIL, NOMBRE_USUARIO, CONTRASENIA, ESTADO, FECHA_NACIMIENTO) 
VALUES ('23456789', 'María', 'González', 2, 1, 'aux@hospital.com', 'aux_admin', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iKTVEFDi', 'ACTIVO', TO_DATE('1990-07-22', 'YYYY-MM-DD'));

INSERT INTO USUARIOS (CEDULA, NOMBRE, APELLIDO, ID_PERFIL, ID_INSTITUCION, EMAIL, NOMBRE_USUARIO, CONTRASENIA, ESTADO, FECHA_NACIMIENTO) 
VALUES ('34567890', 'Carlos', 'Rodríguez', 3, 1, 'tecnico@hospital.com', 'tecnico', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iKTVEFDi', 'ACTIVO', TO_DATE('1988-11-10', 'YYYY-MM-DD'));

INSERT INTO USUARIOS (CEDULA, NOMBRE, APELLIDO, ID_PERFIL, ID_INSTITUCION, EMAIL, NOMBRE_USUARIO, CONTRASENIA, ESTADO, FECHA_NACIMIENTO) 
VALUES ('45678901', 'Ana', 'López', 4, 1, 'usuario@hospital.com', 'usuario', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iKTVEFDi', 'ACTIVO', TO_DATE('1992-05-18', 'YYYY-MM-DD'));

INSERT INTO USUARIOS (CEDULA, NOMBRE, APELLIDO, ID_PERFIL, ID_INSTITUCION, EMAIL, NOMBRE_USUARIO, CONTRASENIA, ESTADO, FECHA_NACIMIENTO) 
VALUES ('56789012', 'Luis', 'Martínez', 1, 2, 'admin@clinica.com', 'admin_clinica', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iKTVEFDi', 'ACTIVO', TO_DATE('1983-09-25', 'YYYY-MM-DD'));

-- =====================================================
-- NIVEL 4: TABLAS QUE DEPENDEN DE USUARIOS
-- =====================================================

-- 13. USUARIOS_TELEFONOS
INSERT INTO USUARIOS_TELEFONOS (ID_USUARIO, NUMERO) VALUES (1, '099123456');
INSERT INTO USUARIOS_TELEFONOS (ID_USUARIO, NUMERO) VALUES (1, '099654321');
INSERT INTO USUARIOS_TELEFONOS (ID_USUARIO, NUMERO) VALUES (2, '099234567');
INSERT INTO USUARIOS_TELEFONOS (ID_USUARIO, NUMERO) VALUES (3, '099345678');
INSERT INTO USUARIOS_TELEFONOS (ID_USUARIO, NUMERO) VALUES (4, '099456789');

-- =====================================================
-- NIVEL 5: TABLAS QUE DEPENDEN DE EQUIPOS Y UBICACIONES
-- =====================================================

-- 14. EQUIPOS
INSERT INTO EQUIPOS (ID_INTERNO, ID_UBICACION, NRO_SERIE, NOMBRE, ID_TIPO, GARANTIA, ESTADO, ID_PROVEEDOR, ID_PAIS, ID_MODELO, FECHA_ADQUISICION) 
VALUES ('MON001', 1, 'SN123456789', 'Monitor Multiparamétrico', 1, TO_DATE('2025-01-15', 'YYYY-MM-DD'), 'ACTIVO', 1, 1, 1, TO_DATE('2023-01-15', 'YYYY-MM-DD'));

INSERT INTO EQUIPOS (ID_INTERNO, ID_UBICACION, NRO_SERIE, NOMBRE, ID_TIPO, GARANTIA, ESTADO, ID_PROVEEDOR, ID_PAIS, ID_MODELO, FECHA_ADQUISICION) 
VALUES ('MON002', 2, 'SN123456790', 'Monitor Multiparamétrico', 1, TO_DATE('2025-02-20', 'YYYY-MM-DD'), 'ACTIVO', 1, 1, 1, TO_DATE('2023-02-20', 'YYYY-MM-DD'));

INSERT INTO EQUIPOS (ID_INTERNO, ID_UBICACION, NRO_SERIE, NOMBRE, ID_TIPO, GARANTIA, ESTADO, ID_PROVEEDOR, ID_PAIS, ID_MODELO, FECHA_ADQUISICION) 
VALUES ('VENT001', 1, 'SN987654321', 'Ventilador Mecánico', 2, TO_DATE('2025-11-10', 'YYYY-MM-DD'), 'ACTIVO', 2, 2, 5, TO_DATE('2022-11-10', 'YYYY-MM-DD'));

INSERT INTO EQUIPOS (ID_INTERNO, ID_UBICACION, NRO_SERIE, NOMBRE, ID_TIPO, GARANTIA, ESTADO, ID_PROVEEDOR, ID_PAIS, ID_MODELO, FECHA_ADQUISICION) 
VALUES ('BOMBA001', 3, 'SN555666777', 'Bomba de Infusión', 3, TO_DATE('2024-03-05', 'YYYY-MM-DD'), 'ACTIVO', 3, 3, 3, TO_DATE('2023-03-05', 'YYYY-MM-DD'));

INSERT INTO EQUIPOS (ID_INTERNO, ID_UBICACION, NRO_SERIE, NOMBRE, ID_TIPO, GARANTIA, ESTADO, ID_PROVEEDOR, ID_PAIS, ID_MODELO, FECHA_ADQUISICION) 
VALUES ('DESF001', 5, 'SN111222333', 'Desfibrilador', 4, TO_DATE('2027-08-15', 'YYYY-MM-DD'), 'ACTIVO', 4, 4, 4, TO_DATE('2022-08-15', 'YYYY-MM-DD'));

-- =====================================================
-- NIVEL 6: TABLAS QUE DEPENDEN DE USUARIOS Y EQUIPOS
-- =====================================================

-- 15. INTERVENCIONES
INSERT INTO INTERVENCIONES (ID_USUARIO, ID_TIPO, ID_EQUIPO, MOTIVO, FECHA_HORA, COMENTARIOS) 
VALUES (3, 1, 1, 'Mantenimiento preventivo mensual', TO_DATE('2024-01-15 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Equipo funcionando correctamente');

INSERT INTO INTERVENCIONES (ID_USUARIO, ID_TIPO, ID_EQUIPO, MOTIVO, FECHA_HORA, COMENTARIOS) 
VALUES (3, 2, 2, 'Reparación de pantalla', TO_DATE('2024-01-10 14:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'Pantalla con fallas de visualización');

INSERT INTO INTERVENCIONES (ID_USUARIO, ID_TIPO, ID_EQUIPO, MOTIVO, FECHA_HORA, COMENTARIOS) 
VALUES (3, 3, 3, 'Calibración anual', TO_DATE('2024-01-05 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Calibración exitosa');

INSERT INTO INTERVENCIONES (ID_USUARIO, ID_TIPO, ID_EQUIPO, MOTIVO, FECHA_HORA, COMENTARIOS) 
VALUES (3, 4, 4, 'Reparación de motor', TO_DATE('2024-01-12 16:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Motor reemplazado');

-- =====================================================
-- NIVEL 7: TABLAS QUE DEPENDEN DE EQUIPOS Y UBICACIONES
-- =====================================================

-- 16. EQUIPOS_UBICACIONES
INSERT INTO EQUIPOS_UBICACIONES (ID_EQUIPO, ID_UBICACION, FECHA, USUARIO, OBSERVACIONES) 
VALUES (1, 1, TO_DATE('2023-01-15', 'YYYY-MM-DD'), 1, 'Instalación inicial');

INSERT INTO EQUIPOS_UBICACIONES (ID_EQUIPO, ID_UBICACION, FECHA, USUARIO, OBSERVACIONES) 
VALUES (2, 2, TO_DATE('2023-02-20', 'YYYY-MM-DD'), 1, 'Instalación inicial');

INSERT INTO EQUIPOS_UBICACIONES (ID_EQUIPO, ID_UBICACION, FECHA, USUARIO, OBSERVACIONES) 
VALUES (3, 1, TO_DATE('2022-11-10', 'YYYY-MM-DD'), 1, 'Instalación inicial');

INSERT INTO EQUIPOS_UBICACIONES (ID_EQUIPO, ID_UBICACION, FECHA, USUARIO, OBSERVACIONES) 
VALUES (4, 3, TO_DATE('2023-03-05', 'YYYY-MM-DD'), 1, 'Instalación inicial');

INSERT INTO EQUIPOS_UBICACIONES (ID_EQUIPO, ID_UBICACION, FECHA, USUARIO, OBSERVACIONES) 
VALUES (5, 5, TO_DATE('2022-08-15', 'YYYY-MM-DD'), 1, 'Instalación inicial');

-- =====================================================
-- NIVEL 8: TABLAS DE AUDITORÍA Y BAJAS
-- =====================================================

-- 17. AUDITORIAS
INSERT INTO AUDITORIAS (FECHA_HORA, ID_USUARIO, ID_OPERACION) 
VALUES (TO_DATE('2024-01-15 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1, 1);

INSERT INTO AUDITORIAS (FECHA_HORA, ID_USUARIO, ID_OPERACION) 
VALUES (TO_DATE('2024-01-15 10:30:00', 'YYYY-MM-DD HH24:MI:SS'), 2, 2);

INSERT INTO AUDITORIAS (FECHA_HORA, ID_USUARIO, ID_OPERACION) 
VALUES (TO_DATE('2024-01-15 14:00:00', 'YYYY-MM-DD HH24:MI:SS'), 3, 3);

INSERT INTO AUDITORIAS (FECHA_HORA, ID_USUARIO, ID_OPERACION) 
VALUES (TO_DATE('2024-01-15 16:45:00', 'YYYY-MM-DD HH24:MI:SS'), 1, 4);

-- 18. BAJA_EQUIPOS
INSERT INTO BAJA_EQUIPOS (ID_USUARIO, ID_EQUIPO, RAZON, FECHA, ESTADO, COMENTARIOS) 
VALUES (1, 1, 'Vida útil agotada', TO_DATE('2024-01-20', 'YYYY-MM-DD'), 'ACTIVO', 'Equipo reemplazado por modelo más nuevo');

-- 19. BAJA_UBICACIONES
INSERT INTO BAJA_UBICACIONES (ID_USUARIO, ID_UBICACION, RAZON, COMENTARIO, FECHA) 
VALUES (1, 7, 'Renovación de instalaciones', 'Ubicación en remodelación', TO_DATE('2024-01-25', 'YYYY-MM-DD'));

-- =====================================================
-- NIVEL 9: TABLAS DE RELACIÓN
-- =====================================================

-- 20. FUNCIONALIDADES_PERFILES
INSERT INTO FUNCIONALIDADES_PERFILES (ID_FUNCIONALIDAD, ID_PERFIL) VALUES (1, 1); -- Admin puede gestionar usuarios
INSERT INTO FUNCIONALIDADES_PERFILES (ID_FUNCIONALIDAD, ID_PERFIL) VALUES (1, 2); -- Aux admin puede gestionar usuarios
INSERT INTO FUNCIONALIDADES_PERFILES (ID_FUNCIONALIDAD, ID_PERFIL) VALUES (2, 1); -- Admin puede gestionar equipos
INSERT INTO FUNCIONALIDADES_PERFILES (ID_FUNCIONALIDAD, ID_PERFIL) VALUES (2, 2); -- Aux admin puede gestionar equipos
INSERT INTO FUNCIONALIDADES_PERFILES (ID_FUNCIONALIDAD, ID_PERFIL) VALUES (2, 3); -- Técnico puede gestionar equipos
INSERT INTO FUNCIONALIDADES_PERFILES (ID_FUNCIONALIDAD, ID_PERFIL) VALUES (3, 1); -- Admin puede gestionar ubicaciones
INSERT INTO FUNCIONALIDADES_PERFILES (ID_FUNCIONALIDAD, ID_PERFIL) VALUES (3, 2); -- Aux admin puede gestionar ubicaciones
INSERT INTO FUNCIONALIDADES_PERFILES (ID_FUNCIONALIDAD, ID_PERFIL) VALUES (4, 1); -- Admin puede gestionar intervenciones
INSERT INTO FUNCIONALIDADES_PERFILES (ID_FUNCIONALIDAD, ID_PERFIL) VALUES (4, 2); -- Aux admin puede gestionar intervenciones
INSERT INTO FUNCIONALIDADES_PERFILES (ID_FUNCIONALIDAD, ID_PERFIL) VALUES (4, 3); -- Técnico puede gestionar intervenciones
INSERT INTO FUNCIONALIDADES_PERFILES (ID_FUNCIONALIDAD, ID_PERFIL) VALUES (5, 1); -- Solo admin puede ver reportes
INSERT INTO FUNCIONALIDADES_PERFILES (ID_FUNCIONALIDAD, ID_PERFIL) VALUES (5, 2); -- Aux admin puede ver reportes

-- =====================================================
-- COMMIT PARA CONFIRMAR TODOS LOS DATOS
-- =====================================================
COMMIT;

-- =====================================================
-- VERIFICACIÓN DE DATOS INSERTADOS
-- =====================================================
SELECT 'OPERACIONES' as tabla, COUNT(*) as cantidad FROM OPERACIONES
UNION ALL
SELECT 'INSTITUCIONES', COUNT(*) FROM INSTITUCIONES
UNION ALL
SELECT 'PERFILES', COUNT(*) FROM PERFILES
UNION ALL
SELECT 'FUNCIONALIDADES', COUNT(*) FROM FUNCIONALIDADES
UNION ALL
SELECT 'TIPOS_INTERVENCIONES', COUNT(*) FROM TIPOS_INTERVENCIONES
UNION ALL
SELECT 'TIPOS_EQUIPOS', COUNT(*) FROM TIPOS_EQUIPOS
UNION ALL
SELECT 'MARCAS_MODELO', COUNT(*) FROM MARCAS_MODELO
UNION ALL
SELECT 'PAISES', COUNT(*) FROM PAISES
UNION ALL
SELECT 'PROVEEDORES_EQUIPOS', COUNT(*) FROM PROVEEDORES_EQUIPOS
UNION ALL
SELECT 'MODELOS_EQUIPOS', COUNT(*) FROM MODELOS_EQUIPOS
UNION ALL
SELECT 'UBICACIONES', COUNT(*) FROM UBICACIONES
UNION ALL
SELECT 'USUARIOS', COUNT(*) FROM USUARIOS
UNION ALL
SELECT 'USUARIOS_TELEFONOS', COUNT(*) FROM USUARIOS_TELEFONOS
UNION ALL
SELECT 'EQUIPOS', COUNT(*) FROM EQUIPOS
UNION ALL
SELECT 'INTERVENCIONES', COUNT(*) FROM INTERVENCIONES
UNION ALL
SELECT 'EQUIPOS_UBICACIONES', COUNT(*) FROM EQUIPOS_UBICACIONES
UNION ALL
SELECT 'AUDITORIAS', COUNT(*) FROM AUDITORIAS
UNION ALL
SELECT 'BAJA_EQUIPOS', COUNT(*) FROM BAJA_EQUIPOS
UNION ALL
SELECT 'BAJA_UBICACIONES', COUNT(*) FROM BAJA_UBICACIONES
UNION ALL
SELECT 'FUNCIONALIDADES_PERFILES', COUNT(*) FROM FUNCIONALIDADES_PERFILES; 